#ifndef CIFRASYNC_COMMON_CONSTANTS_H
#define CIFRASYNC_COMMON_CONSTANTS_H

#define CS_PATH_CAP 4096U
#define CS_HASH_HEX_LEN 64U
#define CS_HASH_HEX_BUFSZ (CS_HASH_HEX_LEN + 1U)
#define CS_ISO8601_BUFSZ 21U
#define CS_MAX_LABEL_LEN 128U

#endif
